-- ============================================================
-- Script de seed para producción - Chemiconsult
-- Generado desde base de desarrollo (Supabase dev)
-- Ejecutar en una base vacía antes de iniciar la app
-- ============================================================

BEGIN;

-- ── MATRICES ────────────────────────────────────────────────
INSERT INTO "MATRIZ" ("NOMBRE") VALUES
  ('Líquida'),
  ('Aire'),
  ('Emisión gaseosa'),
  ('Sólido/semisólido');

-- ── METODOLOGÍAS ─────────────────────────────────────────────
INSERT INTO "METODOLOGIA" ("NOMBRE") VALUES
  ('Cono Imhoff'),
  ('EPA 418.1'),
  ('EPA 8015'),
  ('OSN'),
  ('St. Methods 2320 B'),
  ('St. Methods 2350 B'),
  ('St. Methods 2540 C'),
  ('St. Methods 2540 D'),
  ('St. Methods 2550 B'),
  ('St. Methods 3111 B'),
  ('St. Methods 3112 B'),
  ('St. Methods 3113 B'),
  ('St. Methods 3500-Cr D'),
  ('St. Methods 4500 B B'),
  ('St. Methods 4500 CN C y E'),
  ('St. Methods 4500 CN E'),
  ('St. Methods 4500 N org B (NTK)'),
  ('St. Methods 4500 NH3+ F'),
  ('St. Methods 4500 Norg B'),
  ('St. Methods 4500 P C'),
  ('St. Methods 4500 S=D'),
  ('St. Methods 4500-Cl G'),
  ('St. Methods 4500-H+ B'),
  ('St. Methods 4500-SO4-2 E'),
  ('St. Methods 5210 B'),
  ('St. Methods 5220 D'),
  ('St. Methods 5520 B'),
  ('St. Methods 5530 C'),
  ('St. Methods 5540 C'),
  ('St. Methods 9223 A'),
  ('Fotometría de llama'),
  ('St. Methods 2120 B'),
  ('St. Methods 2130 B'),
  ('St. Methods 2340 C'),
  ('St. Methods 2510'),
  ('St. Methods 4500 Cl- C'),
  ('St. Methods 4500 F D'),
  ('St. Methods 4500 NO2-B'),
  ('St. Methods 4500 NO3- B'),
  ('St. Methods 4500-O G'),
  ('St. Methods 5310 B'),
  ('St. Methods 6232 B'),
  ('St. Methods 9213 B'),
  ('St. Methods 9215 B'),
  ('St. Methods 9221 D');

-- ── PARÁMETROS (unidades corregidas) ──────────────────────────
-- Temperatura: °C  (dev tenía mg/l)
-- Conductividad eléctrica: µS/cm  (dev tenía mg/l)
-- Olor: NULL  (dev tenía '-')
-- Coliformes fecales deduplicado (dev tenía dos filas idénticas)
INSERT INTO "PARAMETRO" ("NOMBRE", "UNIDAD", "ACTIVO") VALUES
  ('Alcalinidad total',                              'mg/l', true),
  ('Alcalinidad de bicarbonatos',                    'mg/l', true),
  ('Alcalinidad de carbonatos',                      'mg/l', true),
  ('Aluminio',                                       'mg/l', true),
  ('Amonio',                                         'mg/l', true),
  ('Antimonio',                                      'mg/l', true),
  ('Arsénico',                                       'mg/l', true),
  ('Bario',                                          'mg/l', true),
  ('Benceno',                                        'mg/l', true),
  ('Boro',                                           'mg/l', true),
  ('Bromato',                                        'mg/l', true),
  ('Cadmio',                                         'mg/l', true),
  ('Calcio',                                         'mg/l', true),
  ('Carbono orgánico total',                         'mg/l', true),
  ('Cianuros destructibles por cloración',           'mg/l', true),
  ('Cianuros totales',                               'mg/l', true),
  ('Cloro libre',                                    'mg/l', true),
  ('Clorofila',                                      'mg/l', true),
  ('Cloruros',                                       'mg/l', true),
  ('Cobalto',                                        'mg/l', true),
  ('Coliformes fecales (UFC/100ml)',                 'UFC/100ml', true),
  ('Coliformes totales',                             NULL, true),
  ('Color',                                          'Pt-Co', true),
  ('Compuestos fenólicos',                           'mg/l', true),
  ('Conductividad eléctrica',                        'µS/cm', true),
  ('Cromo VI',                                       'mg/l', true),
  ('Cromo total',                                    'mg/l', true),
  ('Cromo III',                                      'mg/l', true),
  ('Demanda bioquímica de oxígeno',                  'mg/l', true),
  ('Demanda de cloro',                               'mg/l', true),
  ('Detergentes (SAAM)',                             'mg/l', true),
  ('Dureza total',                                   'mg/l', true),
  ('Enterococos',                                    'mg/l', true),
  ('Escherichia coli',                               'mg/l', true),
  ('Etilbenceno',                                    NULL, true),
  ('Fluoruro total',                                 'mg/l', true),
  ('Fósforo total',                                  'mg/l', true),
  ('Hidrocarburos totales del petróleo',             'mg/l', true),
  ('Hierro total',                                   'mg/l', true),
  ('Investigación de Escherichia coli',              NULL, true),
  ('Investigación de Pseudomona aeruginosa',         NULL, true),
  ('Magnesio',                                       'mg/l', true),
  ('Manganeso total',                                'mg/l', true),
  ('Mercurio total',                                 'mg/l', true),
  ('Molibdeno',                                      'mg/l', true),
  ('Níquel total',                                   'mg/l', true),
  ('Nitratos',                                       'mg/l', true),
  ('Nitritos',                                       'mg/l', true),
  ('Nitrógeno amoniacal',                            'mg/l', true),
  ('Nitrógeno de nitratos',                          'mg/l', true),
  ('Nitrógeno de nitritos',                          'mg/l', true),
  ('Nitrógeno orgánico',                             'mg/l', true),
  ('Nitrógeno total Kjeldahl',                       'mg/l', true),
  ('Olor',                                           NULL, true),
  ('Oxígeno consumido al KMnO4',                     'mg/l', true),
  ('Oxígeno disuelto',                               'mg/l', true),
  ('PCB''s (compuestos bifenilos policlorados)',      'mg/l', true),
  ('pH',                                             'UpH', true),
  ('Plaguicidas Organoclorados',                     'mg/l', true),
  ('Plaguicidas Organofosforados',                   'mg/l', true),
  ('Plata',                                          'mg/l', true),
  ('Plomo',                                          'mg/l', true),
  ('Potasio',                                        'mg/l', true),
  ('Recuento de Bacterias aerobias mesófilas',       'UFC/ml', true),
  ('Selenio total',                                  'mg/l', true),
  ('Silice',                                         'mg/l', true),
  ('Silicio',                                        'mg/l', true),
  ('Sodio',                                          'mg/l', true),
  ('Sólidos disueltos totales',                      'mg/l', true),
  ('Sólidos sedimentables en 10''',                  'ml/l', true),
  ('Sólidos sedimentables en 2hs',                   'ml/l', true),
  ('Sólidos suspendidos totales',                    'mg/l', true),
  ('Sólidos totales',                                'mg/l', true),
  ('Sulfatos',                                       'mg/l', true),
  ('Sulfuros',                                       'mg/l', true),
  ('Sustancias solubles en éter etílico (SSEE)',     'mg/l', true),
  ('Talio',                                          'mg/l', true),
  ('Temperatura',                                    '°C', true),
  ('Tolueno',                                        NULL, true),
  ('Turbiedad',                                      'NTU', true),
  ('Vanadio',                                        'mg/l', true),
  ('Xilenos',                                        NULL, true),
  ('Zinc total',                                     'mg/l', true);

-- ── RESOLUCIONES ─────────────────────────────────────────────
INSERT INTO "RESOLUCION" ("NOMBRE", "DESCRIPCION", "TIENE_DESTINO", "MATRIZ_ID")
VALUES
  ('Res 336/06',
   'Resolución de vuelco de efluentes líquidos',
   true,
   (SELECT id FROM "MATRIZ" WHERE "NOMBRE" = 'Líquida')),
  ('Res 283/19',
   'Resolución de vuelco de efluentes líquidos (actualización)',
   true,
   (SELECT id FROM "MATRIZ" WHERE "NOMBRE" = 'Líquida')),
  ('CAA',
   'Código Alimentario Argentino - Valores máximos',
   false,
   (SELECT id FROM "MATRIZ" WHERE "NOMBRE" = 'Líquida')),
  ('Ley 19587 - Decreto 351/79',
   'Higiene y seguridad en el trabajo',
   false,
   (SELECT id FROM "MATRIZ" WHERE "NOMBRE" = 'Líquida'));

-- ── DESTINOS REGULATORIOS ─────────────────────────────────────
INSERT INTO "RESOL_DESTINO" ("NOMBRE", "RESOLUCION_ID")
VALUES
  ('Colectora cloacal',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Res 336/06')),
  ('Cond. pluvial o cuerpo de agua superficial',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Res 336/06')),
  ('Absorción por el suelo',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Res 336/06')),
  ('Colectora cloacal',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Res 283/19')),
  ('Cond. pluvial o cuerpo de agua superficial',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Res 283/19')),
  ('Absorción por el suelo',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Res 283/19')),
  ('Único',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'CAA')),
  ('Único',
   (SELECT id FROM "RESOLUCION" WHERE "NOMBRE" = 'Ley 19587 - Decreto 351/79'));

-- ── PARÁMETROS POR DESTINO ────────────────────────────────────
-- Columnas: RESOL_DESTINO_ID, PARAMETRO_ID, UNIDAD, TIPO_LIMITE,
--           VALOR_MIN, VALOR_MAX, LIMITE_TEXTO, ACTIVO
-- Lookup de IDs por nombre para ser independiente de secuencias
WITH
  destinos AS (
    SELECT rd.id, r."NOMBRE" AS res, rd."NOMBRE" AS dest
    FROM "RESOL_DESTINO" rd
    JOIN "RESOLUCION" r ON rd."RESOLUCION_ID" = r.id
  ),
  params AS (
    SELECT DISTINCT ON ("NOMBRE") id, "NOMBRE"
    FROM "PARAMETRO"
    ORDER BY "NOMBRE", id
  ),
  datos (res, dest, param, unidad, tipo_limite, valor_min, valor_max, limite_texto, activo) AS (
    VALUES
    -- ── Res 336/06 › Colectora cloacal ──────────────────────
    ('Res 336/06','Colectora cloacal','Aluminio',               'mg/l',     'RANGO', 5::numeric,    6::numeric,    null::text, null::boolean),
    ('Res 336/06','Colectora cloacal','Arsénico',               'mg/l',     'MAX',   null,          0.5,           null, null),
    ('Res 336/06','Colectora cloacal','Bario',                  'mg/l',     'MAX',   null,          2,             null, null),
    ('Res 336/06','Colectora cloacal','Boro',                   'mg/l',     'MAX',   null,          2,             null, null),
    ('Res 336/06','Colectora cloacal','Cadmio',                 'mg/l',     'MAX',   null,          0.5,           null, null),
    ('Res 336/06','Colectora cloacal','Carbono orgánico total', 'mg/l',     'TEXTO', null,          null,          'No exigido', null),
    ('Res 336/06','Colectora cloacal','Cianuros totales',       'mg/l',     'MAX',   null,          0.1,           null, null),
    ('Res 336/06','Colectora cloacal','Cloro libre',            'mg/l',     'TEXTO', null,          null,          'No exigido', null),
    ('Res 336/06','Colectora cloacal','Cobalto',                'mg/l',     'MAX',   null,          2,             null, null),
    ('Res 336/06','Colectora cloacal','Compuestos fenólicos',   'mg/l',     'MAX',   null,          2,             null, null),
    ('Res 336/06','Colectora cloacal','Cromo total',            'mg/l',     'MAX',   null,          2,             null, null),
    ('Res 336/06','Colectora cloacal','Cromo VI',               'mg/l',     'MAX',   null,          0.2,           null, null),
    ('Res 336/06','Colectora cloacal','Demanda bioquímica de oxígeno','mg/l','MAX',  null,          200,           null, null),
    ('Res 336/06','Colectora cloacal','Detergentes (SAAM)',     'mg/l',     'MAX',   null,          10,            null, null),
    ('Res 336/06','Colectora cloacal','Fósforo total',          'mg/l',     'MAX',   null,          10,            null, null),
    ('Res 336/06','Colectora cloacal','Hidrocarburos totales del petróleo','mg/l','MAX',null,       30,            null, null),
    ('Res 336/06','Colectora cloacal','Hierro total',           'mg/l',     'MAX',   null,          10,            null, null),
    ('Res 336/06','Colectora cloacal','Manganeso total',        'mg/l',     'MAX',   null,          1,             null, null),
    ('Res 336/06','Colectora cloacal','Mercurio total',         'mg/l',     'MAX',   null,          0.02,          null, null),
    ('Res 336/06','Colectora cloacal','Nitrógeno amoniacal',    'mg/l',     'MAX',   null,          75,            null, null),
    ('Res 336/06','Colectora cloacal','Nitrógeno orgánico',     'mg/l',     'MAX',   null,          30,            null, null),
    ('Res 336/06','Colectora cloacal','Nitrógeno total Kjeldahl','mg/l',    'MAX',   null,          105,           null, null),
    ('Res 336/06','Colectora cloacal','pH',                     'UpH',      'RANGO', 7,             10,            null, null),
    ('Res 336/06','Colectora cloacal','Plaguicidas Organoclorados','mg/l',  'MAX',   null,          0.5,           null, null),
    ('Res 336/06','Colectora cloacal','Plaguicidas Organofosforados','mg/l','MAX',   null,          1,             null, null),
    ('Res 336/06','Colectora cloacal','Plomo',                  'mg/l',     'MAX',   null,          1,             null, null),
    ('Res 336/06','Colectora cloacal','Selenio total',          'mg/l',     'MAX',   null,          0.1,           null, null),
    ('Res 336/06','Colectora cloacal','Sólidos sedimentables en 10''','ml/l','TEXTO',null,         null,          'Ausente', null),
    ('Res 336/06','Colectora cloacal','Sólidos sedimentables en 2hs','ml/l','MAX',   null,          5,             null, null),
    ('Res 336/06','Colectora cloacal','Sulfatos',               'mg/l',     'MAX',   null,          1000,          null, null),
    ('Res 336/06','Colectora cloacal','Sulfuros',               'mg/l',     'MAX',   null,          2,             null, null),
    ('Res 336/06','Colectora cloacal','Sustancias solubles en éter etílico (SSEE)','mg/l','MAX',null,100,        null, null),
    ('Res 336/06','Colectora cloacal','Temperatura',            '°C',       'MAX',   null,          45,            null, null),
    ('Res 336/06','Colectora cloacal','Zinc total',             'mg/l',     'MAX',   null,          5,             null, false),
    -- ── Res 336/06 › Cond. pluvial ──────────────────────────
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Aluminio',               'mg/l','RANGO',5,       6,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Arsénico',               'mg/l','MAX',  null,    0.5,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Bario',                  'mg/l','MAX',  null,    2,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Boro',                   'mg/l','MAX',  null,    2,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Cadmio',                 'mg/l','MAX',  null,    0.1,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Carbono orgánico total', 'mg/l','TEXTO',null,   null, 'No exigido', null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Cianuros totales',       'mg/l','MAX',  null,    0.1,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Cloro libre',            'mg/l','MAX',  null,    0.5,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Cobalto',                'mg/l','MAX',  null,    2,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Compuestos fenólicos',   'mg/l','MAX',  null,    0.5,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Cromo total',            'mg/l','MAX',  null,    2,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Cromo VI',               'mg/l','MAX',  null,    0.2,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Demanda bioquímica de oxígeno','mg/l','MAX',null,50,   null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Detergentes (SAAM)',     'mg/l','MAX',  null,    2,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Fósforo total',          'mg/l','MAX',  null,    1,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Hidrocarburos totales del petróleo','mg/l','MAX',null,30,null,null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Hierro total',           'mg/l','MAX',  null,    2,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Manganeso total',        'mg/l','MAX',  null,    0.5,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Mercurio total',         'mg/l','MAX',  null,    5,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Nitrógeno amoniacal',    'mg/l','MAX',  null,    25,   null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Nitrógeno orgánico',     'mg/l','MAX',  null,    10,   null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Nitrógeno total Kjeldahl','mg/l','MAX', null,   35,   null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','pH',                     'UpH', 'RANGO',6.5,    10,   null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Plaguicidas Organoclorados','mg/l','MAX',null,  1,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Plaguicidas Organofosforados','mg/l','MAX',null,0.1,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Plomo',                  'mg/l','MAX',  null,    0.1,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Selenio total',          'mg/l','MAX',  null,    0.1,  null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Sólidos sedimentables en 10''','ml/l','TEXTO',null,null,'Ausente',null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Sólidos sedimentables en 2hs','ml/l','MAX',null,1,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Sulfatos',               'mg/l','TEXTO',null,   null, 'No exigido', null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Sulfuros',               'mg/l','MAX',  null,    1,    null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Sustancias solubles en éter etílico (SSEE)','mg/l','MAX',null,50,null,null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Temperatura',            '°C',  'MAX',  null,    45,   null, null),
    ('Res 336/06','Cond. pluvial o cuerpo de agua superficial','Zinc total',             'mg/l','MAX',  null,    2,    null, false),
    -- ── Res 336/06 › Absorción por el suelo ─────────────────
    ('Res 336/06','Absorción por el suelo','Aluminio',               'mg/l','RANGO',5,    6,    null, null),
    ('Res 336/06','Absorción por el suelo','Arsénico',               'mg/l','MAX',  null,  0.1,  null, null),
    ('Res 336/06','Absorción por el suelo','Bario',                  'mg/l','MAX',  null,  1,    null, null),
    ('Res 336/06','Absorción por el suelo','Boro',                   'mg/l','MAX',  null,  1,    null, null),
    ('Res 336/06','Absorción por el suelo','Cadmio',                 'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Carbono orgánico total', 'mg/l','TEXTO',null,  null, 'No exigido', null),
    ('Res 336/06','Absorción por el suelo','Cianuros totales',       'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Cloro libre',            'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Cobalto',                'mg/l','MAX',  null,  1,    null, null),
    ('Res 336/06','Absorción por el suelo','Compuestos fenólicos',   'mg/l','MAX',  null,  0.1,  null, null),
    ('Res 336/06','Absorción por el suelo','Cromo total',            'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Cromo VI',               'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Demanda bioquímica de oxígeno','mg/l','MAX',null,200, null, null),
    ('Res 336/06','Absorción por el suelo','Detergentes (SAAM)',     'mg/l','MAX',  null,  2,    null, null),
    ('Res 336/06','Absorción por el suelo','Fósforo total',          'mg/l','MAX',  null,  10,   null, null),
    ('Res 336/06','Absorción por el suelo','Hidrocarburos totales del petróleo','mg/l','TEXTO',null,null,'Ausente',null),
    ('Res 336/06','Absorción por el suelo','Hierro total',           'mg/l','MAX',  null,  0.1,  null, null),
    ('Res 336/06','Absorción por el suelo','Manganeso total',        'mg/l','MAX',  null,  0.1,  null, null),
    ('Res 336/06','Absorción por el suelo','Mercurio total',         'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Nitrógeno amoniacal',    'mg/l','MAX',  null,  75,   null, null),
    ('Res 336/06','Absorción por el suelo','Nitrógeno orgánico',     'mg/l','MAX',  null,  30,   null, null),
    ('Res 336/06','Absorción por el suelo','Nitrógeno total Kjeldahl','mg/l','MAX', null,  105,  null, null),
    ('Res 336/06','Absorción por el suelo','pH',                     'UpH', 'RANGO',6.5,  10,   null, null),
    ('Res 336/06','Absorción por el suelo','Plaguicidas Organoclorados','mg/l','MAX',null,  0.05, null, null),
    ('Res 336/06','Absorción por el suelo','Plaguicidas Organofosforados','mg/l','TEXTO',null,null,'Ausente',null),
    ('Res 336/06','Absorción por el suelo','Plomo',                  'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Selenio total',          'mg/l','TEXTO',null,  null, 'Ausente', null),
    ('Res 336/06','Absorción por el suelo','Sólidos sedimentables en 10''','ml/l','TEXTO',null,null,'Ausente',null),
    ('Res 336/06','Absorción por el suelo','Sólidos sedimentables en 2hs','ml/l','MAX',null,5,   null, null),
    ('Res 336/06','Absorción por el suelo','Sulfatos',               'mg/l','MAX',  null,  1000, null, null),
    ('Res 336/06','Absorción por el suelo','Sulfuros',               'mg/l','MAX',  null,  5,    null, null),
    ('Res 336/06','Absorción por el suelo','Sustancias solubles en éter etílico (SSEE)','mg/l','MAX',null,50,null,null),
    ('Res 336/06','Absorción por el suelo','Temperatura',            '°C',  'MAX',  null,  45,   null, null),
    ('Res 336/06','Absorción por el suelo','Zinc total',             'mg/l','MAX',  null,  1,    null, false),
    -- ── Res 283/19 › Colectora cloacal ──────────────────────
    ('Res 283/19','Colectora cloacal','Aluminio',                          'mg/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Colectora cloacal','Arsénico',                          'mg/l','MAX',  null, 0.5,  null, null),
    ('Res 283/19','Colectora cloacal','Bario',                             'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Colectora cloacal','Boro',                              'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Colectora cloacal','Cadmio',                            'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Colectora cloacal','Cianuros destructibles por cloración','mg/l','MAX',null,0.1,  null, null),
    ('Res 283/19','Colectora cloacal','Cianuros totales',                  'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Colectora cloacal','Cloro libre',                       'mg/l','TEXTO',null, null, 'No exigido', null),
    ('Res 283/19','Colectora cloacal','Cobalto',                           'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Colectora cloacal','Coliformes fecales (UFC/100ml)',     'UFC/100ml','TEXTO',null,null,'No exigido',null),
    ('Res 283/19','Colectora cloacal','Compuestos fenólicos',              'mg/l','MAX',  null, 0.5,  null, null),
    ('Res 283/19','Colectora cloacal','Cromo total',                       'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Colectora cloacal','Cromo VI',                          'mg/l','MAX',  null, 0.2,  null, null),
    ('Res 283/19','Colectora cloacal','Demanda bioquímica de oxígeno',     'mg/l','MAX',  null, 200,  null, null),
    ('Res 283/19','Colectora cloacal','Detergentes (SAAM)',                'mg/l','MAX',  null, 10,   null, null),
    ('Res 283/19','Colectora cloacal','Fósforo total',                     'mg/l','MAX',  null, 10,   null, null),
    ('Res 283/19','Colectora cloacal','Hidrocarburos totales del petróleo','mg/l','MAX',  null, 30,   null, null),
    ('Res 283/19','Colectora cloacal','Hierro total',                      'mg/l','MAX',  null, 10,   null, null),
    ('Res 283/19','Colectora cloacal','Manganeso total',                   'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Colectora cloacal','Mercurio total',                    'mg/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Colectora cloacal','Níquel total',                      'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Colectora cloacal','Nitrógeno amoniacal',               'mg/l','MAX',  null, 75,   null, null),
    ('Res 283/19','Colectora cloacal','Nitrógeno total Kjeldahl',          'mg/l','MAX',  null, 105,  null, null),
    ('Res 283/19','Colectora cloacal','pH',                                'UpH', 'RANGO',5.5,  10,   null, null),
    ('Res 283/19','Colectora cloacal','Plomo',                             'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Colectora cloacal','Selenio total',                     'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Colectora cloacal','Sólidos sedimentables en 10''',    'ml/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Colectora cloacal','Sólidos sedimentables en 2hs',     'ml/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Colectora cloacal','Sólidos suspendidos totales',       'mg/l','TEXTO',null, null, 'No exigido', null),
    ('Res 283/19','Colectora cloacal','Sulfatos',                          'mg/l','MAX',  null, 1000, null, null),
    ('Res 283/19','Colectora cloacal','Sulfuros',                          'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Colectora cloacal','Sustancias solubles en éter etílico (SSEE)','mg/l','MAX',null,100,null,null),
    ('Res 283/19','Colectora cloacal','Temperatura',                       '°C',  'MAX',  null, 45,   null, null),
    ('Res 283/19','Colectora cloacal','Zinc total',                        'mg/l','MAX',  null, 5,    null, null),
    -- ── Res 283/19 › Cond. pluvial ──────────────────────────
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Aluminio',               'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Arsénico',               'mg/l','MAX',  null, 0.5,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Bario',                  'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Boro',                   'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cadmio',                 'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cianuros destructibles por cloración','mg/l','MAX',null,0.1,null,null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cianuros totales',       'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cloro libre',            'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cobalto',                'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Coliformes fecales (UFC/100ml)','UFC/100ml','MAX',null,500,null,null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Compuestos fenólicos',   'mg/l','MAX',  null, 0.5,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cromo total',            'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Cromo VI',               'mg/l','MAX',  null, 0.2,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Demanda bioquímica de oxígeno','mg/l','MAX',null,30,null,null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Detergentes (SAAM)',     'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Fósforo total',          'mg/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Hidrocarburos totales del petróleo','mg/l','MAX',null,30,null,null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Hierro total',           'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Manganeso total',        'mg/l','MAX',  null, 0.5,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Mercurio total',         'mg/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Níquel total',           'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Nitrógeno amoniacal',    'mg/l','MAX',  null, 25,   null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Nitrógeno total Kjeldahl','mg/l','MAX', null, 35,   null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','pH',                     'UpH', 'RANGO',6.5,  9,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Plomo',                  'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Selenio total',          'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Sólidos sedimentables en 10''','ml/l','MAX',null,0.1,null,null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Sólidos sedimentables en 2hs','ml/l','MAX',null,1,  null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Sólidos suspendidos totales','mg/l','MAX',null,35, null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Sulfatos',               'mg/l','TEXTO',null,  null,'No exigido',null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Sulfuros',               'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Sustancias solubles en éter etílico (SSEE)','mg/l','MAX',null,50,null,null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Temperatura',            '°C',  'MAX',  null, 45,   null, null),
    ('Res 283/19','Cond. pluvial o cuerpo de agua superficial','Zinc total',             'mg/l','MAX',  null, 2,    null, null),
    -- ── Res 283/19 › Absorción por el suelo ─────────────────
    ('Res 283/19','Absorción por el suelo','Aluminio',                          'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Absorción por el suelo','Arsénico',                          'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Absorción por el suelo','Bario',                             'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Absorción por el suelo','Boro',                              'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Absorción por el suelo','Cobalto',                           'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Absorción por el suelo','Coliformes fecales (UFC/100ml)',     'UFC/100ml','MAX',null,500,  null, null),
    ('Res 283/19','Absorción por el suelo','Compuestos fenólicos',              'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Absorción por el suelo','Cromo total',                       'mg/l','TEXTO',null, null, 'Ref c', null),
    ('Res 283/19','Absorción por el suelo','Cromo VI',                          'mg/l','TEXTO',null, null, 'Ref c', null),
    ('Res 283/19','Absorción por el suelo','Demanda bioquímica de oxígeno',     'mg/l','MAX',  null, 200,  null, null),
    ('Res 283/19','Absorción por el suelo','Detergentes (SAAM)',                'mg/l','MAX',  null, 2,    null, null),
    ('Res 283/19','Absorción por el suelo','Fósforo total',                     'mg/l','MAX',  null, 10,   null, null),
    ('Res 283/19','Absorción por el suelo','Hidrocarburos totales del petróleo','mg/l','TEXTO',null, null, 'Ref c', null),
    ('Res 283/19','Absorción por el suelo','Hierro total',                      'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Absorción por el suelo','Manganeso total',                   'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Absorción por el suelo','Mercurio total',                    'mg/l','TEXTO',null, null, 'Ref c', null),
    ('Res 283/19','Absorción por el suelo','Níquel total',                      'mg/l','MAX',  null, 1,    null, null),
    ('Res 283/19','Absorción por el suelo','Nitrógeno amoniacal',               'mg/l','MAX',  null, 75,   null, null),
    ('Res 283/19','Absorción por el suelo','Nitrógeno total Kjeldahl',          'mg/l','MAX',  null, 105,  null, null),
    ('Res 283/19','Absorción por el suelo','pH',                                'UpH', 'RANGO',6.5,  9,    null, null),
    ('Res 283/19','Absorción por el suelo','Plomo',                             'mg/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Absorción por el suelo','Selenio total',                     'mg/l','TEXTO',null, null, 'Ref c', null),
    ('Res 283/19','Absorción por el suelo','Sólidos sedimentables en 10''',    'ml/l','MAX',  null, 0.1,  null, null),
    ('Res 283/19','Absorción por el suelo','Sólidos sedimentables en 2hs',     'ml/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Absorción por el suelo','Sólidos suspendidos totales',       'mg/l','TEXTO',null, null, 'No exigido', null),
    ('Res 283/19','Absorción por el suelo','Sulfatos',                          'mg/l','MAX',  null, 1000, null, null),
    ('Res 283/19','Absorción por el suelo','Sulfuros',                          'mg/l','MAX',  null, 5,    null, null),
    ('Res 283/19','Absorción por el suelo','Sustancias solubles en éter etílico (SSEE)','mg/l','MAX',null,50,null,null),
    ('Res 283/19','Absorción por el suelo','Temperatura',                       '°C',  'MAX',  null, 45,   null, null),
    ('Res 283/19','Absorción por el suelo','Zinc total',                        'mg/l','MAX',  null, 1,    null, null),
    -- ── CAA › Único ─────────────────────────────────────────
    ('CAA','Único','Aluminio',                                   'mg/l',     'MAX',  null,  0.2,    null, null),
    ('CAA','Único','Amonio',                                     'mg/l',     'MAX',  null,  0.2,    null, null),
    ('CAA','Único','Antimonio',                                  'mg/l',     'MAX',  null,  0.02,   null, null),
    ('CAA','Único','Arsénico',                                   'mg/l',     'RANGO',0.05,  0.01,   '0,01/0,05', null),
    ('CAA','Único','Boro',                                       'mg/l',     'MAX',  null,  2.4,    null, null),
    ('CAA','Único','Bromato',                                    'mg/l',     'MAX',  null,  0.02,   null, null),
    ('CAA','Único','Cadmio',                                     'mg/l',     'MAX',  null,  0.01,   null, null),
    ('CAA','Único','Cianuros totales',                           'mg/l',     'MAX',  null,  0.1,    null, null),
    ('CAA','Único','Cloro libre',                                'mg/l',     'MIN',  0.2,   null,   null, null),
    ('CAA','Único','Cloruros',                                   'mg/l',     'MAX',  null,  350,    null, null),
    ('CAA','Único','Color',                                      'Pt-Co',    'MAX',  null,  5,      null, null),
    ('CAA','Único','Cromo total',                                'mg/l',     'MAX',  null,  0.05,   null, null),
    ('CAA','Único','Dureza total',                               'mg/l',     'MAX',  null,  400,    null, null),
    ('CAA','Único','Fluoruro total',                             'mg/l',     'RANGO',0.7,   1.2,    null, null),
    ('CAA','Único','Hierro total',                               'mg/l',     'MAX',  null,  0.3,    null, null),
    ('CAA','Único','Investigación de Escherichia coli',          null,       'TEXTO',null,  null,   'Ausente', null),
    ('CAA','Único','Investigación de Pseudomona aeruginosa',     null,       'TEXTO',null,  null,   'Ausente', null),
    ('CAA','Único','Manganeso total',                            'mg/l',     'MAX',  null,  0.1,    null, null),
    ('CAA','Único','Mercurio total',                             'mg/l',     'MAX',  null,  0.001,  null, null),
    ('CAA','Único','Níquel total',                               'mg/l',     'MAX',  null,  0.02,   null, null),
    ('CAA','Único','Nitratos',                                   'mg/l',     'MAX',  null,  45,     null, null),
    ('CAA','Único','Nitritos',                                   'mg/l',     'MAX',  null,  0.1,    null, null),
    ('CAA','Único','Olor',                                       null,       'TEXTO',null,  null,   'Sin olores extraños', null),
    ('CAA','Único','pH',                                         'UpH',      'RANGO',6.5,   8.5,    null, null),
    ('CAA','Único','Plata',                                      'mg/l',     'MAX',  null,  0.05,   null, null),
    ('CAA','Único','Plomo',                                      'mg/l',     'MAX',  null,  0.05,   null, null),
    ('CAA','Único','Recuento de Bacterias aerobias mesófilas',   'UFC/ml',   'MAX',  null,  500,    null, null),
    ('CAA','Único','Selenio total',                              'mg/l',     'MAX',  null,  0.01,   null, null),
    ('CAA','Único','Sólidos disueltos totales',                  'mg/l',     'MAX',  null,  1500,   null, null),
    ('CAA','Único','Sulfatos',                                   'mg/l',     'MAX',  null,  400,    null, null),
    ('CAA','Único','Zinc total',                                 'mg/l',     'MAX',  null,  5,      null, null)
  )
INSERT INTO "RESOL_DESTINO_PARAM"
  ("RESOL_DESTINO_ID", "PARAMETRO_ID", "UNIDAD",
   "TIPO_LIMITE", "VALOR_MIN", "VALOR_MAX", "LIMITE_TEXTO", "ACTIVO")
SELECT
  d.id,
  p.id,
  datos.unidad,
  datos.tipo_limite,
  datos.valor_min,
  datos.valor_max,
  datos.limite_texto,
  datos.activo
FROM datos
JOIN destinos d ON d.res = datos.res AND d.dest = datos.dest
JOIN params   p ON p."NOMBRE" = datos.param;

COMMIT;
