-- ══════════════════════════════════════════════
--  PARAMETROS
-- ══════════════════════════════════════════════

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('pH','unidades',6.5,8.5,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Turbidez','NTU',0.0,3.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Color','unidades Pt-Co',0.0,15.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Conductividad','µS/cm',0.0,1500.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Temperatura','°C',0.0,25.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Sólidos Disueltos Totales','mg/L',0.0,1500.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Sólidos Suspendidos Totales','mg/L',0.0,35.0,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Dureza Total','mg/L CaCO3',0.0,400.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Alcalinidad Total','mg/L CaCO3',0.0,350.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Cloruros','mg/L',0.0,350.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Sulfatos','mg/L',0.0,400.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Nitratos','mg/L',0.0,45.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Nitritos','mg/L',0.0,0.1,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Amonio','mg/L',0.0,0.2,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Fósforo Total','mg/L',0.0,0.5,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Fluoruros','mg/L',0.0,1.5,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Hierro Total','mg/L',0.0,0.3,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Manganeso','mg/L',0.0,0.1,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Sodio','mg/L',0.0,200.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Arsénico','mg/L',0.0,0.01,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Plomo','mg/L',0.0,0.01,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Cromo Total','mg/L',0.0,0.05,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Cadmio','mg/L',0.0,0.005,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Mercurio','mg/L',0.0,0.001,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Níquel','mg/L',0.0,0.02,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Zinc','mg/L',0.0,5.0,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Cobre','mg/L',0.0,2.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('DBO5','mg/L',0.0,30.0,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('DQO','mg/L',0.0,250.0,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Aceites y Grasas','mg/L',0.0,50.0,'Ley 24051',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Detergentes (SAAM)','mg/L',0.0,0.5,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Fenoles','mg/L',0.0,0.001,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Cloro Residual Libre','mg/L',0.2,1.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Coliformes Totales','UFC/100mL',0.0,0.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Coliformes Fecales','UFC/100mL',0.0,0.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Escherichia coli','UFC/100mL',0.0,0.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Bacterias Aerobias Totales','UFC/mL',0.0,500.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "PARAMETRO" ("NOMBRE","UNIDAD","VALOR_MIN","VALOR_MAX","NORMA_REFERENCIA","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Pseudomonas aeruginosa','UFC/100mL',0.0,0.0,'CAA Art. 982',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

-- ══════════════════════════════════════════════
--  TIPO_MUESTRA
-- ══════════════════════════════════════════════

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Agua potable','Análisis fisicoquímico y bacteriológico de agua de red pública',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Agua de pozo','Análisis de agua subterránea para consumo humano o riego',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Agua residual','Análisis de aguas residuales domiciliarias o mixtas',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Efluente industrial','Análisis de efluentes provenientes de procesos industriales',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Efluente cloacal','Análisis de efluentes cloacales tratados o sin tratar',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Suelo agrícola','Análisis físico-químico de suelos para uso agropecuario',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

INSERT INTO "TIPO_MUESTRA" ("NOMBRE","DESCRIPCION","ACTIVO","CREATED_DATE","UPDATE_DATE")
VALUES ('Agua superficial','Análisis de ríos, lagos, canales y cuerpos de agua superficiales',true,CURRENT_DATE,CURRENT_DATE)
    ON CONFLICT DO NOTHING;

-- ══════════════════════════════════════════════
--  TIPO_MUESTRA_PARAM — asociaciones
-- ══════════════════════════════════════════════

-- ── Agua potable ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Agua potable'
  AND p."NOMBRE" IN ('pH','Turbidez','Color','Conductividad','Sólidos Disueltos Totales',
                     'Dureza Total','Alcalinidad Total','Cloruros','Sulfatos','Nitratos','Nitritos',
                     'Fluoruros','Hierro Total','Manganeso','Sodio','Arsénico','Plomo',
                     'Cloro Residual Libre','Coliformes Totales','Coliformes Fecales',
                     'Escherichia coli','Bacterias Aerobias Totales')
    ON CONFLICT DO NOTHING;

-- ── Agua de pozo ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Agua de pozo'
  AND p."NOMBRE" IN ('pH','Turbidez','Color','Conductividad','Sólidos Disueltos Totales',
                     'Dureza Total','Alcalinidad Total','Cloruros','Sulfatos','Nitratos','Nitritos',
                     'Amonio','Fluoruros','Hierro Total','Manganeso','Sodio','Arsénico','Plomo',
                     'Coliformes Totales','Coliformes Fecales','Escherichia coli')
    ON CONFLICT DO NOTHING;

-- ── Agua residual ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Agua residual'
  AND p."NOMBRE" IN ('pH','Conductividad','Sólidos Suspendidos Totales','Sólidos Disueltos Totales',
                     'DBO5','DQO','Amonio','Nitratos','Nitritos','Fósforo Total',
                     'Aceites y Grasas','Detergentes (SAAM)','Coliformes Totales',
                     'Coliformes Fecales','Escherichia coli')
    ON CONFLICT DO NOTHING;

-- ── Efluente industrial ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Efluente industrial'
  AND p."NOMBRE" IN ('pH','Conductividad','Temperatura','Sólidos Suspendidos Totales',
                     'Sólidos Disueltos Totales','DBO5','DQO','Aceites y Grasas','Fenoles',
                     'Detergentes (SAAM)','Fósforo Total','Amonio','Cromo Total','Plomo',
                     'Zinc','Cobre','Níquel','Cadmio','Mercurio','Arsénico')
    ON CONFLICT DO NOTHING;

-- ── Efluente cloacal ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Efluente cloacal'
  AND p."NOMBRE" IN ('pH','Conductividad','Sólidos Suspendidos Totales','DBO5','DQO',
                     'Amonio','Nitratos','Nitritos','Fósforo Total','Aceites y Grasas',
                     'Detergentes (SAAM)','Coliformes Totales','Coliformes Fecales',
                     'Escherichia coli','Pseudomonas aeruginosa')
    ON CONFLICT DO NOTHING;

-- ── Suelo agrícola ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Suelo agrícola'
  AND p."NOMBRE" IN ('pH','Conductividad','Fósforo Total','Nitratos','Nitritos',
                     'Arsénico','Plomo','Cadmio','Cromo Total','Zinc','Cobre','Níquel')
    ON CONFLICT DO NOTHING;

-- ── Agua superficial ──
INSERT INTO "TIPO_MUESTRA_PARAM" ("TIPO_MUESTRA_ID","PARAMETRO_ID")
SELECT tm.id, p.id FROM "TIPO_MUESTRA" tm, "PARAMETRO" p
WHERE tm."NOMBRE" = 'Agua superficial'
  AND p."NOMBRE" IN ('pH','Turbidez','Color','Conductividad','Temperatura',
                     'Sólidos Suspendidos Totales','Sólidos Disueltos Totales','DBO5','DQO',
                     'Amonio','Nitratos','Fósforo Total','Aceites y Grasas','Arsénico','Plomo',
                     'Cromo Total','Coliformes Totales','Coliformes Fecales','Escherichia coli')
    ON CONFLICT DO NOTHING;
